### PR TITLE
improve database config

### PR DESCRIPTION
**Pull request by STOzaki**
Just added time zone to the url to connect to our database

### CODE REVIEW

**Comment by kingjon3377** [comment]
My only objection is that the database config (or at least the username and password) isn't supposed to be in the version-control repository in the first place.

**Comment by STOzaki** [comment]
Wait, why is it not suppose to? I guess not but at least it gives people who use this repo to have an idea of what to put in the data config file. Otherwise, they could be stumped on this problem for a while.

**Comment by kingjon3377** [comment]
(As was discussed back in the first couple of weeks ...) Primarily, as part of the security "defense in depth," don't publish any actual credentials anywhere public. This is why `database-config.properties` exists in the first place: it was the file created to be added to `.gitignore` so we could hide these essential properties without hiding *all* properties.

> at least it gives people who use this repo to have an idea of what to put in the data config file. Otherwise, they could be stumped on this problem for a while.

It would be fine to have *obviously fake* sample credentials in a public file (though maybe name it `database-config.properties.sample` so it doesn't get picked up by Spring), with something like

```
spring.datasource.url = jdbc:mysql://databaseHost:databasePort/library?useSSL=false&serverTimezone=UTC
spring.datasource.username = databaseUsername
spring.datasource.password = databasePassword
```

... but while the URL isn't all *that* important to keep private, username and password `root` and `root` is entirely too likely to be real.

A second reason is that this is the part of the configuration that is most likely to change from development machine to development machine, and so if it's in version control people will either be essentially maintaining local patches or committing conflicting data to the repository.

**Comment by henryjyc** [comment]
All I'm seeing in this commit is that change in the jdbc line so I'm just going to merge it. The login credentials thing can be handled in another commit

**Pull request merged**
